apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instagram
  template:
    metadata:
      labels:
        app: instagram
    spec:
      containers:
      - name: instagram
        image: instagramacr123.azurecr.io/instagram-app:v1
        ports:
        - containerPort: 3000
